### PR TITLE
bump electron and hide from dock/taskbar

### PR DESCRIPTION
**Pull request by mafintosh**
makes it not show a generic dock icon on osx. have only tested this on osx, fyi

### CODE REVIEW

**Comment by feross** [comment]
LGTM!

**Comment by mappum** [comment]
Thanks!

Although we'll have to figure out why the tests fail on Linux (looks like the Electron process doesn't get started properly).

**Comment by mafintosh** [comment]
@mappum i think that might be the app.dock.hide() line thats failing on ubuntu

**Comment by feross** [comment]
Oh, yes, you have to do `if (app.dock)` since that doesn't exist on non OS X platforms.

**Comment by mappum** [comment]
Thanks, I was meaning to upgrade to electron 1 for a while 👍 And it's great that now there won't be an ugly dock icon.

**Pull request merged**
