### PR TITLE
Make xvfb optional (for Windows users)

### PR DESCRIPTION
**Pull request by feross**
For https://github.com/feross/webtorrent/issues/743

### CODE REVIEW

**Comment by mappum** [comment]
:+1: Thanks

**Comment by feross** [comment]
Cheers :)

**Comment by feross** [comment]
Since this was released as minor, looks like `electron-webrtc` needs a version bump!

**Comment by mappum** [comment]
Thanks, updated in `electron-webrtc@0.2.2`.

**Pull request merged**
