### PR TITLE
chore: update deps to latest

### PR DESCRIPTION
**Pull request by daviddias**
Hey @mappum! 

Just went did a dep update and tests continue to passing flawlessly 🌟

Mind merging and releasing so that users of electron-eval use the latest electron?

### CODE REVIEW

**Comment by mappum** [comment]
Thanks @diasdavid, I appreciate the PR!

Sorry for my weird build system, but do you mind running `npm run source` and amending your commit so that the babel build isn't committed to the repo (the `lib` directory should be a symlink to `src` instead of a dir)?

**Comment by diasdavid** [comment]
No problem. Done! :)

**Comment by mappum** [comment]
Sweet 💯

**Comment by diasdavid** [comment]
awesome. Could you also publish to npm?

**Comment by mappum** [comment]
Published as version `0.9.10`

**Pull request merged**
